#4 support large result sets (#32)
* #4 Refactor cursor: extract cursor data

* #4 Fetch batches

* Adapt rockspec, run tests via luarocks

* Speedup test: create schema only when required

* Close result set when closing the cursor

* Add connection properties

* #4 Add unit tests

* Apply suggestions from code review

Co-authored-by: Sebastian Bär <redcatbear@ursus-minor.de>

* Implement review findings by @redcatbear 

* Pin link checker to working version

Error: Unable to resolve action `gaurav-nelson/github-action-markdown-link-check@v1.0.13`, unable to find version `v1.0.13`

Co-authored-by: Sebastian Bär <redcatbear@ursus-minor.de>